name: Deploy Trade Journal to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # or your desired version

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup SSH Directory and Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 24.199.116.19 >> ~/.ssh/known_hosts
    
      - name: Rsync files to remote server
        run: |
          rsync -r --delete --exclude='.git' --exclude='node_modules' /home/runner/work/trade-journal/trade-journal/build/ root@24.199.116.19:/var/www/trade-journal/build
        env:
          RSYNC_PASSWORD: ${{ secrets.SERVER_SSH_KEY }}